### ISSUE TITLE
Add incl ext to php7 for symfony2

### ISSUE THREAD

**Issue by ko22009** [nanoninja/php-fpm#1]
RUN apt-get update \
  && apt-get install -y zlib1g-dev libicu-dev g++ \
  && docker-php-ext-configure intl \
  && docker-php-ext-install intl

**Comment by nanoninja** [comment]
Hello @ko22009,

I [added](https://github.com/nanoninja/php-fpm/commit/0dfaec62f61343599bff8f846b7f3992a97b4207) intl extension.

Thank for your feedback.
