### ISSUE TITLE
Add support for the imap extension

### ISSUE THREAD

**Issue by Berdir** [nanoninja/php-fpm#2]
Would be useful to have that, maybe not enabled by default but make it easy to do so?

Found https://github.com/docker-library/php/issues/244 with instructions on what someone had to do to get that working.

**Comment by nanoninja** [comment]
Hi @Berdir,

I'm working on it, you can already find what you are looking for on the following link for the version of PHP7.2 which will also be the master. Soon PHP 7.1

[PHP-FPM 7.2 Dockerfile](https://github.com/nanoninja/php-fpm/blob/7.2/Dockerfile#L40)

```sh
sudo docker pull nanoninja/php-fpm:7.2
```
