### ISSUE TITLE
Problem during building image FROM php:5.6.32-fpm

### ISSUE THREAD

**Issue by dkosourov** [nanoninja/php-fpm#7]
During running 'docker-compose build fpm' me and my team are getting following error:
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'fpm' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 100
If we trying to get that URL we are getting code from the image:

![image](https://user-images.githubusercontent.com/43283320/55163883-a6a26a80-517b-11e9-8f38-2fa361edc3ff.png)

**Comment by nanoninja** [comment]
hi dkosourov,

Can I see part of the file? I believe the name of the image you specified is incorrect.

docker-compose:

`
image: nanoninja/php-fpm:5.6.32
`

Could you give me more information please?

Because you talk to me about docker-compose and you use the word FROM that match the dockerfile.
Maybe you wanted to make the next order?

`docker image build -t yourimagename .`

**Comment by dkosourov** [comment]
Here is the part of my project's docker-compose.yml
![image](https://user-images.githubusercontent.com/43283320/55229223-72878200-522d-11e9-9426-cb02f8156951.png)
And here is the code from docker file
![image](https://user-images.githubusercontent.com/43283320/55230141-f6db0480-522f-11e9-8ec8-f4858418456a.png)
I'm guessing porblem is on line 10.
It worked perfect until this week

**Comment by dkosourov** [comment]
Here is what I've got during build

> denis@denis-multicon ~/IdeaProjects/sandbox $ docker-compose build fpm
> Building fpm
> Step 1/19 : FROM php:5.6.32-fpm
> 5.6.32-fpm: Pulling from library/php
> f49cf87b52c1: Pull complete
> 185616061386: Pull complete
> 5fc132db2e0d: Pull complete
> 00c1c323341a: Pull complete
> 768019bfa727: Pull complete
> 176545257697: Pull complete
> 85554aba6d66: Pull complete
> d40ba977efd9: Pull complete
> a1a7f433be4d: Pull complete
> ae13c2bca4ce: Pull complete
> Digest: sha256:da15a9d6c78bc761c9c04df83e4969eb754cf218491b03ee6c1115c9ee30e8fd
> Status: Downloaded newer image for php:5.6.32-fpm
>  ---> 57a0f87bcae9
> Step 2/19 : MAINTAINER Vincent Letourneau <vincent@nanoninja.com>
>  ---> Running in e4181f6a9a9a
> Removing intermediate container e4181f6a9a9a
>  ---> 00efe6ae6d16
> Step 3/19 : ADD oracle/instantclient-basic-linux.x64-11.2.0.4.0.zip /tmp/instantclient-basic-linux.x64-11.2.0.4.0.zip
>  ---> a91d2c1d7137
> Step 4/19 : ADD oracle/instantclient-sdk-linux.x64-11.2.0.4.0.zip /tmp/instantclient-sdk-linux.x64-11.2.0.4.0.zip
>  ---> 2a6c9b05a61a
> Step 5/19 : ADD oracle/instantclient-sqlplus-linux.x64-11.2.0.4.0.zip /tmp/instantclient-sqlplus-linux.x64-11.2.0.4.0.zip
>  ---> 04b355414161
> Step 6/19 : RUN apt-get update
>  ---> Running in 3c91bd27a3d1
> Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
> Ign http://deb.debian.org jessie InRelease
> Ign http://deb.debian.org jessie-updates InRelease
> Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
> Ign http://deb.debian.org jessie-updates Release.gpg
> Get:3 http://deb.debian.org jessie Release [148 kB]
> Ign http://deb.debian.org jessie-updates Release
> Get:4 http://security.debian.org jessie/updates/main amd64 Packages [824 kB]
> Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
> Err http://deb.debian.org jessie-updates/main amd64 Packages
>   
> Err http://deb.debian.org jessie-updates/main amd64 Packages
>   
> Err http://deb.debian.org jessie-updates/main amd64 Packages
>   
> Err http://deb.debian.org jessie-updates/main amd64 Packages
>   404  Not Found
> Fetched 10.1 MB in 7s (1371 kB/s)
> W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ERROR: Service 'fpm' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 100

**Comment by dkosourov** [comment]
This is the result of CURLing problem link
![image](https://user-images.githubusercontent.com/43283320/55230069-c5facf80-522f-11e9-9dc4-5a1555a23548.png)

**Comment by dkosourov** [comment]
Ok, I've just digged deeper (means 'opened google') and now I think I need to apologize and close the issue. Because there is a plenty of solutions of this problem on stackoverflow and it is not dependent from docker file - https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository

**Comment by dkosourov** [comment]
Forgive me, pal) Please, decline this issue.
