### ISSUE TITLE
mcrypt not enabled in the php7.1.14 image

### ISSUE THREAD

**Issue by adknownadmin** [nanoninja/php-fpm#8]
Hi,

I found I was unable to use the mcrypt while using the php7.1.14 container, I got a " function mcrypt_decrypt was not found" error.

This is fixed by adding **docker-php-ext-install -j$(nproc) mcrypt** to the Dockerfile.

Example working Dockerfile: 

```
FROM nanoninja/php-fpm:7.1.14

RUN docker-php-ext-install -j$(nproc) mcrypt
```

I can open a PR if that'd be preferred

regards,
Matt

**Comment by nanoninja** [comment]
Hi,

It's late but I added mcrypt.

Vincent.
